version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - localstack
    environment:
      - ENVIRONMENT=production
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
  pytest:
    build: .
    command: pytest tests/  # The directory where your tests are located
    depends_on:
      - app
      - localstack
    environment:
      - ENVIRONMENT=test
